##  create
POST http://localhost:10000/api/compra/ HTTP/1.1
Content-Type: application/json

{
    "usuario": 1,
    "videojuego": 1
}

###

##  read
GET http://localhost:10000/api/compra/2 HTTP/1.1
Content-Type: application/json
###
