### Create document OK: PONER UNA RUTA CORRECTA Y NOMBRE FICHERO 'prueba.pdf'
POST http://localhost:10000/api/docs HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="idVideojuego"

2
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nombreFichero"

prueba.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="comentario"

Documento de prueba
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="multipart"; filename="ManualXsara.pdf"
Content-Type: application/pdf

< /home/vesprada/Escriptori/prueba.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### update document OK: PONER UNA RUTA CORRECTA Y NOMBRE FICHERO 'prueba.pdf'
PUT http://localhost:10000/api/docs/1 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="idVideojuego"

3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="nombreFichero"

prueba.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="comentario"

Documento de prueba con comentarios
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="multipart"; filename="ManualXsara.pdf"
Content-Type: application/pdf

< /home/vesprada/Escriptori/pruebaDos.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Read document
GET http://localhost:10000/api/docs/1 HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "VIDEOJUEGO_DOC_NOT_FOUND"
GET http://localhost:10000/api/docs/200 HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "VIDEOJUEGO_DOC_NOT_FOUND"
GET http://localhost:10000/api/docs/1a HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "ID_FORMAT_INVALID"
DELETE http://localhost:10000/api/docs/a HTTP/1.1
Content-Type: application/json

### Get all
GET http://localhost:10000/api/docs/search HTTP/1.1
Content-Type: application/json

### Get all documents with filters and sorting
GET http://localhost:10000/api/docs/search?filter=nombreFichero:CONTIENE:Xsara&sort=nombreFichero&page=0&size=10 HTTP/1.1
Content-Type: application/json

### Get all documents where 'id' is greater than 1
GET http://localhost:10000/api/docs/search?filter=id:MAYOR_QUE:1&sort=id&page=0&size=10 HTTP/1.1
Content-Type: application/json

### Get all documents where 'id' is less than 5
GET http://localhost:10000/api/docs/search?filter=id:MENOR_QUE:5&sort=id&page=0&size=10 HTTP/1.1
Content-Type: application/json

### Get all documents where 'nombreFichero' contains 'Man'
GET http://localhost:10000/api/docs/search?filter=nombreFichero:CONTIENE:Man&sort=nombreFichero&page=0&size=10 HTTP/1.1
Content-Type: application/json

### Get all documents where 'idVideojuego' equals '2'
GET http://localhost:10000/api/docs/search?filter=idVideojuego:IGUAL:2&sort=id&page=0&size=10 HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "BAD_ATTRIBUTE_FILTER"
GET http://localhost:10000/api/docs/search?filter=invalidAttribute:IGUAL:Simarret&sort=id,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "BAD_FILTER"
GET http://localhost:10000/api/docs/search?filter=id:INVALID_OPERATOR:1&sort=id,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "BAD_ATTRIBUTE_ORDER"
GET http://localhost:10000/api/docs/search?filter=id:IGUAL:1&sort=invalidSortAttribute,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "BAD_OPERATOR_FILTER"
GET http://localhost:10000/api/docs/search?filter=id:CONTIENE:1&sort=id,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json

### 
## para comprobar que realmente hacemos la previsualización
GET http://localhost:10000/api/docs/preview/1 HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "VIDEOJUEGO_DOC_NOT_FOUND"
GET http://localhost:10000/api/docs/preview/200 HTTP/1.1
Content-Type: application/json

### Delete document
DELETE http://localhost:10000/api/docs/1 HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "ID_FORMAT_INVALID"
DELETE http://localhost:10000/api/docs/1a HTTP/1.1
Content-Type: application/json