###
## nuevo incorrecto
POST http://localhost:10000/auth/nuevo HTTP/1.1
Content-Type: application/json

{
  "nickname": "prueba",
  "email": "@",
  "password": "a",
  "roles": ["CLIENTE"]
}

###
## crear nuevo usuario pedro
POST http://localhost:10000/auth/nuevo HTTP/1.1
Content-Type: application/json

{
  "nickname": "pedro",
  "nombre": "Alumno Pedro",
  "email": "pedro.alumno@gmail.com",
  "password": "NoTeLoDigo@1",
  "roles": ["CLIENTE"]
}

###
## login incorrect
POST http://localhost:10000/auth/login HTTP/1.1
Content-Type: application/json

{
  "nickname": "pedro",
  "password": "SiTeLoDigo@1"
}

###
## login ok
POST http://localhost:10000/auth/login HTTP/1.1
Content-Type: application/json

{
  "nickname": "pedro",
  "password": "NoTeLoDigo@1"
}

###
## getCompra usuario pedro con JWT 
GET http://localhost:10000/api/compra/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZWRybyIsImlhdCI6MTc0MDQxOTU0MywiZXhwIjoxNzQwNDU1NTQzfQ.IeN3HCHVfDtsE7bXb5FMp6sSYABSgOsE5eVCfHvMkf4

###
## crear nuevo usuario carlos ok
POST http://localhost:10000/auth/nuevo HTTP/1.1
Content-Type: application/json

{
  "nickname": "carlos",
  "nombre": "Alumno Carlos",
  "email": "carlos.alumno@gmail.com",
  "password": "NoTeLoDigo@1",
  "roles": ["ADMIN","CLIENTE"]
}

###
## login ok
POST http://localhost:10000/auth/login HTTP/1.1
Content-Type: application/json

{
  "nickname": "carlos",
  "password": "NoTeLoDigo@1"
}

###
## getCompra usuario carlos con JWT 
GET http://localhost:10000/api/compra/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYXJsb3MiLCJpYXQiOjE3NDA0MTk1NjcsImV4cCI6MTc0MDQ1NTU2N30.0A5SgAMgjXIrrTVCYYk9MYLFXndSrXRHw-8RYTDXvYY
