###
## create
POST http://localhost:10000/api/videojuego HTTP/1.1
Content-Type: application/json

{
    "nombre": "Simarro Kong",
    "categoria": "Aventura",
    "precio": 39.99
}

###
##  read
GET http://localhost:10000/api/videojuego/2 HTTP/1.1
Content-Type: application/json

###
##  update
PUT http://localhost:10000/api/videojuego/2 HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "nombre": "Simarro of Legends",
    "categoria": "RPG",
    "precio": 0.0
}

###
## getAll  
GET http://localhost:10000/api/videojuegos HTTP/1.1
Content-Type: application/json

###
## getAll  (paginado)
GET http://localhost:10000/api/videojuegos?sort=nombre&page=0&size=5 HTTP/1.1
Content-Type: application/json

###
## getAll (filtrado por nombre)
GET http://localhost:10000/api/videojuegos?filter=nombre:CONTIENE:The HTTP/1.1
Content-Type: application/json

###
## getAll (filtrado por categoria)
GET http://localhost:10000/api/videojuegos?filter=categoria:IGUAL:Aventura HTTP/1.1
Content-Type: application/json

###
## getAll (filtrado por categria)
GET http://localhost:10000/api/videojuegos?filter=categria:IGUAL:Aventura HTTP/1.1
Content-Type: application/json

###
## delete
DELETE  http://localhost:10000/api/videojuego/1 HTTP/1.1
Content-Type: application/json