###
## create
POST http://localhost:10000/api/videojuego HTTP/1.1
Content-Type: application/json

{
    "nombre": "Simarro Kong",
    "categoria": "Aventura",
    "preci": 39.99
}

###
## Error: "errorCode": "VIDEOJUEGO_CREATE_VALIDATION"
POST http://localhost:10000/api/videojuego HTTP/1.1
Content-Type: application/json

{
    "nombr": "Simarro Kong",
    "categori": "Aventura",
    "preci": 39.99
}

###
## Error: "errorCode": "VIDEOJUEGO_CREATE_VALIDATION"
POST http://localhost:10000/api/videojuego HTTP/1.1
Content-Type: application/json

{
    "nombre": "Simarro Kong",
    "categoria": "Aventura"
}

###
##  read
GET http://localhost:10000/api/videojuego/2 HTTP/1.1
Content-Type: application/json

###
## Error: "errorCode": "VIDEOJUEGO_NOT_FOUND"
GET  http://localhost:10000/api/videojuego/2000 HTTP/1.1
Content-Type: application/json

###
## Error: "errorCode": "ID_FORMAT_INVALID"
DELETE  http://localhost:10000/api/videojuego/a HTTP/1.1
Content-Type: application/json

###
##  update
PUT http://localhost:10000/api/videojuego/2 HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "nombre": "Simarro of Legends",
    "categoria": "RPG",
    "precio": 0.0
}

###
##  Error: "errorCode": "VIDEOJUEGO_ID_MISMATCH"
PUT http://localhost:10000/api/videojuego/2 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Simarro of Legends",
    "categoria": "RPG",
    "precio": 0.0
}

###
##  Error: "errorCode": "VIDEOJUEGO_ID_MISMATCH"
PUT http://localhost:10000/api/videojuego/20000 HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "nombre": "Simarro of Legends",
    "categoria": "RPG",
    "precio": 0.0
}

###
##  Error: "errorCode": "VIDEOJUEGO_UPDATE_VALIDATION"
PUT http://localhost:10000/api/videojuego/2 HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "nombre": "Simarro of Legends",
    "categoria": "RPG",
    "preci": 0.0
}


###
## getAll  
GET http://localhost:10000/api/videojuegos HTTP/1.1
Content-Type: application/json

###
## getAll  (paginado)
GET http://localhost:10000/api/videojuegos?sort=nombre&page=0&size=5 HTTP/1.1
Content-Type: application/json

###
## getAll (filtrado por nombre)
GET http://localhost:10000/api/videojuegos?filter=nombre:CONTIENE:The HTTP/1.1
Content-Type: application/json

###
## getAll (filtrado por categoria)
GET http://localhost:10000/api/videojuegos?filter=categoria:IGUAL:Aventura HTTP/1.1
Content-Type: application/json

###
## getAll (filtrado por precio)
GET http://localhost:10000/api/videojuegos?filter=precio:MAYOR_QUE:30 HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "BAD_ATTRIBUTE_FILTER"
GET http://localhost:10000/api/docs/search?filter=invalidAttribute:IGUAL:Simarret&sort=id,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "BAD_FILTER"
GET http://localhost:10000/api/docs/search?filter=id:INVALID_OPERATOR:1&sort=id,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "BAD_ATTRIBUTE_ORDER"
GET http://localhost:10000/api/docs/search?filter=id:IGUAL:1&sort=invalidSortAttribute,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "BAD_OPERATOR_FILTER"
GET http://localhost:10000/api/docs/search?filter=id:CONTIENE:1&sort=id,asc&page=0&size=10 HTTP/1.1
Content-Type: application/json

###
## delete
DELETE  http://localhost:10000/api/videojuego/1 HTTP/1.1
Content-Type: application/json

### Error: "errorCode": "ID_FORMAT_INVALID"
DELETE http://localhost:10000/api/videojuego/e HTTP/1.1
Content-Type: application/json